version: "3.9"

services:

  as:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    extra_hosts:
      - "hostnet:172.19.0.1"
    volumes:
      - "./djangosaml2_sp/:/run/django-identity/djangosaml2_sp/"

  spid-testenv2:
    image: italia/spid-testenv2:1.1.0
    ports:
      - "8088:8088"
    extra_hosts:
      - "hostnet:172.19.0.1"
    volumes:
      - "./configs/spid-testenv2/config.yaml:/app/conf/config.yaml:ro"
      - "./configs/spid-testenv2/users.json:/app/conf/users.json:ro"

  spid-saml-check:
    build:
      context: ./spid-saml-check/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "hostnet:172.19.0.1"
    volumes:
      - "./configs/spid-saml-check/idp.json:/spid-saml-check/spid-validator/config/idp.json:ro"
